Docsal: add init command; use latest version of cli (it includes wp-cli tool)

diff --git a/.docksal/commands/init b/.docksal/commands/init
--- a/.docksal/commands/init
+++ b/.docksal/commands/init
@@ -2,3 +2,150 @@
 set -e
 
 ## Initialize Docksal powered WordPress Installation
+
+# Set to the appropriate site directory
+SITE_DOMAIN='wp.docksal'
+
+# Console colors
+red='\033[0;31m'
+green='\033[0;32m'
+green_bg='\033[42m'
+yellow='\033[1;33m'
+NC='\033[0m'
+
+echo-red () { echo -e "${red}$1${NC}"; }
+echo-green () { echo -e "${green}$1${NC}"; }
+echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
+echo-yellow () { echo -e "${yellow}$1${NC}"; }
+
+# Check whether shell is interactive (otherwise we are running in a non-interactive script environment)
+is_tty ()
+{
+	[[ "$(/usr/bin/tty || true)" != "not a tty" ]]
+}
+
+is_windows ()
+{
+	local res=$(uname | grep 'CYGWIN_NT')
+	if [[ "$res" != "" ]]; then
+		return 0
+	else
+		return 1
+	fi
+}
+
+# Yes/no confirmation dialog with an optional message
+# @param $1 confirmation message
+_confirm ()
+{
+	# Skip checks if not a tty
+	if ! is_tty ; then return 0; fi
+
+	while true; do
+		read -p "$1 [y/n]: " answer
+		case $answer in
+			[Yy]|[Yy][Ee][Ss] )
+				break
+				;;
+			[Nn]|[Nn][Oo] )
+				exit 1
+				;;
+			* )
+				echo 'Please answer yes or no.'
+		esac
+	done
+}
+
+# Copy a settings file from $source to $dest
+# Skips if the $dest already exists.
+_copy_settings_file()
+{
+  local source=${1}
+  local dest=${2}
+
+  if [[ ! -f $dest ]]; then
+    echo "Copying ${dest}..."
+    cp "$source" "$dest"
+  else
+    echo-yellow "${dest} already in place"
+  fi
+}
+
+# Copy settings files
+init_settings ()
+{
+  cd "$GIT_ROOT"
+
+  # docker-compose
+  _copy_settings_file ".docksal/docksal-local-minimal.yml" "docker-compose.yml"
+}
+
+# Generate wp-config.php file
+generate_config ()
+{
+  cd "$GIT_ROOT/docroot"
+
+  fin exec "wp core config --dbname=wordpress --dbuser=wordpress --dbpass=123 --dbhost=db"
+}
+
+# Install the site
+site_install ()
+{
+  cd "$GIT_ROOT/docroot"
+
+  fin exec "wp core install --url=wp.docksal --title=WordPress-site --admin_user=admin --admin_password=123 --admin_email=info@example.com"
+}
+
+# Create a new DB
+# @param $1 DB name
+db_create ()
+{
+  echo-yellow "Creating DB ${1}..."
+
+  local database=${1}
+  local mysql_exec='mysql -h $DB_1_PORT_3306_TCP_ADDR --user=root --password=$DB_1_ENV_MYSQL_ROOT_PASSWORD -e ';
+  local query="DROP DATABASE IF EXISTS ${database}; CREATE DATABASE ${database}; GRANT ALL ON ${database}.* TO "'$DB_1_ENV_MYSQL_USER'"@'%'"
+
+  fin exec "${mysql_exec} \"${query}\""
+}
+
+#-------------------------- Execution --------------------------------
+
+# Set repo root as working directory.
+GIT_ROOT=$(git rev-parse --show-toplevel)
+if [[ -z "$GIT_ROOT" ]]; then
+	echo-red "Git repository was not found"
+	exit 1;
+fi
+cd "$GIT_ROOT"
+
+# Project initialization steps
+echo -e "${green_bg} Step 1 ${NC}${green} Initializing local project configuration...${NC}"
+init_settings
+
+if [[ $DOCKER_RUNNING == "true" ]]; then
+  echo -e "${green_bg} Step 2 ${NC}${green} Recreating services...${NC}"
+  fin reset -f
+else
+  echo -e "${green_bg} Step 2 ${NC}${green} Creating services...${NC}"
+  fin up
+fi
+
+echo "Waiting 10s for MySQL to initialize...";
+sleep 10
+
+echo -e "${green_bg} Step 3 ${NC}${green} Generating wp-config.php file...${NC}"
+generate_config
+
+echo -e "${green_bg} Step 4 ${NC}${green} Installing site...${NC}"
+site_install
+
+
+if is_windows; then
+	echo-green "Add ${SITE_DOMAIN} to your hosts file (/etc/hosts), e.g.:"
+	echo-green "192.168.10.10  ${SITE_DOMAIN}"
+	echo
+fi
+
+echo -en "${green_bg} DONE! ${NC} "
+echo -e "Open ${yellow}http://${SITE_DOMAIN}${NC} in your browser to verify the setup."
